-- 
-- 导出表中的数据 `jieqi_system_blocks`
-- 

INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '本站公告', 'system', '', 'BlockSystemCustom', 4, '本站公告', '', '<br>\r\n欢迎使用 JIEQI CMS，安装完成后请删除install目录，然后进入后台进行参数、用户组、权限和区块的相关设置。\r\n<br><br>\r\n更多程序和使用方面咨询请访问：\r\n<br><br>\r\n<a href="http://www.jieqi.com" target="_blank">http://www.jieqi.com</a>\r\n<br><br>', '', '', 0, 1, 10000, 0, 1, 1, 3, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户登录', 'system', 'block_login', 'BlockSystemLogin', 0, '用户登录', '', '', '', '', 0, 4, 10100, 0, 0, 0, 3, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户登录（AJAX）', 'system', '', 'BlockSystemCustom', 0, '用户登录', '', '<div id="block_login"></div>\r\n<script language="javascript" type="text/javascript">\r\nAjax.Update(''/blockshow.php?module=system&filename=block_login&classname=BlockSystemLogin&vars=&template=&contenttype=4&custom=0&publish=3&hasvars=0'', {outid:''block_login'', tipid:''block_login'', onLoading:''正在载入...''})\r\n</script>', '', '', 0, 1, 10150, 0, 1, 1, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户分类', 'system', 'block_grouplist', 'BlockSystemGrouplist', 0, '用户分类', '', '', '', '', 0, 0, 10300, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '短消息', 'system', 'block_message', 'BlockSystemMessage', 0, '短消息', '', '', '', '', 0, 0, 10400, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户搜索', 'system', 'block_searchuser', 'BlockSystemSearchuser', 0, '用户搜索', '', '', '', '', 0, 0, 10500, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户排行', 'system', 'block_topuser', 'BlockSystemTopuser', 0, '用户排行', '', '', '', '', 0, 0, 10700, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户工具箱', 'system', 'block_userbox', 'BlockSystemUserbox', 0, '用户工具箱', '', '', '', '', 0, 0, 10800, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户设置', 'system', 'block_userset', 'BlockSystemUserset', 0, '用户设置', '', '', '', '', 0, 0, 10900, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '最新用户', 'system', 'block_userlist', 'BlockSystemUserlist', 0, '最新用户', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_userlist.html”，在/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置四个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按用户积分），允许以下几种设置：1、“score” - 按用户积分；2、“experience” - 按经验值；3、“regdate” - 按加入日期；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是用户类别（默认 0 表示所有类别），此处使用得是用户组序号而不是名称，比如“专栏作家”类别序号是 5 ，这里就设置成 5，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “score,20,0,0” 表示显示20个积分最多的用户。', '', 'regdate,15,0,0', 'block_usernew.html', 0, 4, 10900, 1, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '积分排行', 'system', 'block_userlist', 'BlockSystemUserlist', 0, '积分排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_userlist.html”，在/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置四个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按用户积分），允许以下几种设置：1、“score” - 按用户积分；2、“experience” - 按经验值；3、“regdate” - 按加入日期；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是用户类别（默认 0 表示所有类别），此处使用得是用户组序号而不是名称，比如“专栏作家”类别序号是 5 ，这里就设置成 5，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “score,20,0,0” 表示显示20个积分最多的用户。', '', 'score,15,0,0', 'block_userscore.html', 0, 4, 11000, 1, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '经验排行', 'system', 'block_userlist', 'BlockSystemUserlist', 0, '经验排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_userlist.html”，在/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置四个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按用户积分），允许以下几种设置：1、“score” - 按用户积分；2、“experience” - 按经验值；3、“regdate” - 按加入日期；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是用户类别（默认 0 表示所有类别），此处使用得是用户组序号而不是名称，比如“专栏作家”类别序号是 5 ，这里就设置成 5，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “score,20,0,0” 表示显示20个积分最多的用户。', '', 'experience,15,0,0', 'block_userexp.html', 0, 4, 11100, 1, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户列表区块', 'system', 'block_userlist', 'BlockSystemUserlist', 0, '用户排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_userlist.html”，在/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置四个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按用户积分），允许以下几种设置：1、“score” - 按用户积分；2、“experience” - 按经验值；3、“regdate” - 按加入日期；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是用户类别（默认 0 表示所有类别），此处使用得是用户组序号而不是名称，比如“专栏作家”类别序号是 5 ，这里就设置成 5，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “score,20,0,0” 表示显示20个积分最多的用户。', '', 'score,15,0,0', 'block_userlist.html', 0, 4, 11200, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户推荐区块', 'system', 'block_usercommend', 'BlockSystemUsercommend', 0, '用户推荐', '&nbsp;&nbsp;&nbsp;&nbsp;本区块根据设置的参数显示对应ID的用户<br>&nbsp;&nbsp;&nbsp;&nbsp;默认一个参数，设置推荐的用户ID，多个ID用“|”分割，比如 12|34|56', '', '', 'block_usercommend.html', 0, 4, 11250, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户友情连接', 'system', 'block_userlink', 'BlockSystemUserlink', 1, '用户友情连接', '&nbsp;&nbsp;&nbsp;&nbsp;本区块显示某一用户自添加的友情连接<br>&nbsp;&nbsp;&nbsp;&nbsp;允许设置五个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排序字段，允许设置成“toptime”-置顶时间，或者“addtime”-添加时间<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示几条记录，默认10<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是排序方式：0-从大到小，1-从小到大<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是显示哪个用户的友情链接，允许设置成“self”-当前用户，“uid”-url参数里面uid值对应的用户，“0”-所有用户，设置成大于0的一个整数，表示指定这个uid的用户<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是内容过滤，0-都显示，1-显示置顶的链接，2-显示非置顶链接', '', 'toptime,10,0,uid,0', 'block_userlink.html', 0, 4, 11300, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户好友列表', 'system', 'block_ufriends', 'BlockSystemUfriends', 1, '用户好友列表', '&nbsp;&nbsp;&nbsp;&nbsp;本区块显示某一用户好友列表<br>&nbsp;&nbsp;&nbsp;&nbsp;允许设置四个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排序字段，允许设置成“friendsid”-好友记录ID，或者“adddate”-添加时间<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示几条记录，默认10<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是排序方式：0-从大到小，1-从小到大<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是显示哪个用户的好友列表，允许设置成“self”-当前用户，“uid”-url参数里面uid值对应的用户，“0”-所有用户，设置成大于0的一个整数，表示指定这个uid的用户', '', 'friendsid,10,0,uid', 'block_ufriends.html', 0, 4, 11400, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户资料', 'system', 'block_uinfo', 'BlockSystemUinfo', 0, '用户资料', '&nbsp;&nbsp;&nbsp;&nbsp;本区块显示某一用户资料<br>&nbsp;&nbsp;&nbsp;&nbsp;允许设置一个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是显示哪个用户的资料，允许设置成“self”-当前用户，“uid”-url参数里面uid值对应的用户，设置成大于0的一个整数，表示指定这个uid的用户', '', 'uid', 'block_uinfo.html', 0, 4, 11500, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户会客室主题', 'system', 'block_uptopics', 'BlockSystemUptopics', 6, '会客室主题', '&nbsp;&nbsp;&nbsp;&nbsp;本区块显示某一用户会客室主题<br>&nbsp;&nbsp;&nbsp;&nbsp;允许设置七个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排序字段，允许设置成“topicid”-主题序号，“posttime”-发表时间，“replytime”-最后回复时间，“views”-点击数，“replies”-回复数间<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示几条记录，默认10<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是排序方式：0-从大到小，1-从小到大<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是显示哪个用户的友情链接，允许设置成“self”-当前用户，“uid”-url参数里面uid值对应的用户，“0”-所有用户，设置成大于0的一个整数，表示指定这个uid的用户<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是否置顶贴，0-都显示，1-显示置顶，2-显示非置顶<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是否精华贴，0-都显示，1-显示精华，2-显示非精华<br>&nbsp;&nbsp;&nbsp;&nbsp;参数七是否锁定贴，0-都显示，1-显示锁定，2-显示非锁定', '', 'topicid,10,0,uid,0,0,0', 'block_uptopics.html', 0, 4, 11600, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '网页内容调用区块', 'system', 'block_fileget', 'BlockSystemFileget', 0, '', '&nbsp;&nbsp;&nbsp;&nbsp;本区块是通过URL获取网页内容作为自己的区块内容。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置三个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是访问的URL(必须设置)，如 http://www.domain.com/block.php?id=1<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是缓存时间（单位是秒），本参数可以留空或者设置成0，表示使用系统默认缓存时间。设置成-1表示不用缓存，设置大于0的整数表示自定义缓存时间。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是指获取的网页内容编码，留空表示和系统默认编码相同。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “http://www.domain.com/block.php?id=1,1800,utf-8” 表示获取这个网址内容，缓存半个小时，内容编码是utf-8', '', '', '', 0, 4, 12500, 0, 0, 0, 0, 1);

-- 
-- 导出表中的数据 `jieqi_system_configs`
-- 

INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'useradminpnum', '用户管理每页显示数', '50', '管理界面', 0, 3, '', 10100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'userpnum', '用户列表每页显示数', '200', '', 0, 3, '', 10200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'topuserpnum', '用户排行每页显示数', '100', '', 0, 3, '', 10400, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'userlogpnum', '用户日志每页显示数', '50', '', 0, 3, '', 10600, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'onlinetime', '在线统计时间', '1800', '单位“秒”', 0, 3, '', 10800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'messagepnum', '信箱每页显示数', '30', '', 0, 3, '', 10900, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'messagelimit', '信箱最多消息数', '50', '', 0, 3, '', 11000, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'maxdaymsg', '每天允许发消息数', '0', '设置成 0 表示不限制每天发短信数量', 0, 3, '', 11050, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'friendspnum', '好友列表每页显示数', '50', '', 0, 3, '', 11200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'maxfriends', '最多好友数量', '50', '', 0, 3, '', 11300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'checkcodelogin', '登陆时是否使用验证码', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 11900, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'usegd', '系统是否支持GD库', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 12000, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'regtimelimit', '同一IP几个小时内禁止重复注册', '0', '设置成 0 表示不限制', 0, 3, '', 12100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'usernamelimit', '注册用户名限制', '0', '', 0, 7, 'a:2:{i:0;s:20:"允许中英文及数字组合";i:1;s:20:"仅允许英文和数字组合";}', 12200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'avatardir', '会员头像保存目录', 'avatar', '', 0, 1, '', 13100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'avatarurl', '会员头像访问URL', '', '对应保存目录的url，最后不带斜杠，如果留空则系统自动判断', 0, 1, '', 13150, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'avatartype', '头像允许上传的文件类型', '.gif .jpg .jpeg .png', '多个类型用空格分开，如".gif .jpg .jpeg .png"', 0, 1, '', 13200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'avatarcut', '是否要求裁剪头像图片', '1', '裁剪图片需要GD库支持', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 13250, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'avatarsize', '头像文件不得超过几K', '50', '', 0, 3, '', 13300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'ptopicpnum', '会客室主题每页显示数', '0', '', 0, 3, '', 13600, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'ppostpnum', '会客室回复每页显示数', '0', '', 0, 3, '', 13700, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'scoreregister', '注册积分', '10', '', 0, 3, '', 20100, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'scorelogin', '登录积分', '3', '一天计算一次', 0, 3, '', 20200, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'sendmsgscore', '超过每天发消息数后继续发送一条减少积分', '0', '如果设置成 0 则不允许超额发送短信', 0, 3, '', 20250, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'adclickscore', '每次点击广告积分', '1', '需要登陆用户点击有效', 0, 3, '', 20300, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'maxadclick', '每天最多有效广告点击次数', '5', '超过此次数点击广告将不计分', 0, 3, '', 20400, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'ppostneedscore', '多少积分以上允许在会客室发贴', '', '', 0, 3, '', 21000, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'scoreptopic', '会客室发贴增加积分', '', '', 0, 3, '', 21100, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'mailtype', '邮件发送方式', '1', '', 0, 7, 'a:4:{i:0;s:14:"不发送任何邮件";i:1;s:40:"通过 PHP 函数及 UNIX sendmail 发送(推荐)";i:2;s:49:"通过 SOCKET 连接 SMTP 服务器发送(支持 ESMTP 验证)";i:3;s:60:"通过 PHP 函数 SMTP 发送 Email(仅 win32 下有效, 不支持 ESMTP)";}', 30100, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'maildelimiter', '邮件头的分隔符', '1', '', 0, 7, 'a:2:{i:0;s:18:"使用 LF 作为分隔符";i:1;s:20:"使用 CRLF 作为分隔符";}', 30200, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'mailserver', 'SMTP 服务器', '', '如：smtp.jieqi.com', 0, 1, '', 30300, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'mailport', 'SMTP 端口', '25', '默认不需修改', 0, 3, '', 30400, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'mailauth', '是否需要 AUTH LOGIN 验证', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 30500, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'mailfrom', '发信人地址', '', '如果需要验证,必须为本服务器地址。地址写法可以是 webmaster@jieqi.com 或者 JieqiCMS <webmaster@jieqi.com>', 0, 1, '', 30500, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'mailuser', '验证用户名', '', 'SMTP 邮件服务器用户名(如：webmaster@jieqi.com)', 0, 1, '', 30600, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'mailpassword', '验证密码', '', 'SMTP 邮件服务器密码', 0, 1, '', 30700, '邮件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'posttitlemax', '发帖标题最多几个字节', '60', '跟数据结构中的字段长度有关，一般不用修改', 0, 3, '', 40100, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'postintervaltime', '两次发贴最少间隔时间', '0', '单位是秒，设置成 0 表示无时间间隔限制', 0, 3, '', 40200, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'postdenywords', '禁止发表的词语', '', '替换规则每条一行，写法为：“from=to”表示内容“from”将被替换成“to”。也可以只写“from”，这样内容中的“from”会替换成“**”，相当于隐藏关键词效果。', 0, 2, '', 40300, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'postreplacewords', '发帖内容替换', '', '可以设置多个替换规则，每个一行。', 0, 2, '', 40400, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'postminsize', '发帖内容最少字节数', '0', '0 表示不限制', 0, 3, '', 40500, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'postmaxsize', '发帖内容最多字节数', '0', '0 表示不限制', 0, 3, '', 40600, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'postdenyrubbish', '禁止灌水帖子', '0', '被怀疑是灌水的帖子将禁止发表，程序判断不一定准确，请慎用', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 40700, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES (0, 'system', 'postcheckcode', '发帖是否使用验证码', '0', '', 0, 9, 'a:2:{i:7;s:2:"是";i:0;s:2:"否";}', 40800, '内容检查设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_URL', '网站地址', '', '虚拟路径（URL），后面不带斜线', 1, 1, '', 10200, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_SITE_NAME', '网站名称', 'JIEQI CMS', '', 1, 1, '', 10300, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_CONTACT_EMAIL', '联系Email', '', '', 1, 1, '', 10500, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_MAIN_SERVER', '主服务器网址', '', '在使用多服务器情况下设置主服务器网址（如：http://www.domain.com），后面不带斜线，单服务器可以留空', 1, 1, '', 10520, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_USER_ENTRY', '用户入口服务器网址', '', '在使用多服务器情况下设置用户注册、登录、退出等功能的服务器网址（如：http://www.domain.com），后面不带斜线，单服务器可以留空', 1, 1, '', 10530, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_META_KEYWORDS', '网站关键字', '', '      多个关键字用";"隔开(小写分号)', 1, 2, '', 10600, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_META_DESCRIPTION', '网站描述', '', '', 1, 2, '', 10700, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_META_COPYRIGHT', '版权申明', '', '', 1, 2, '', 10800, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_BANNER', 'BANNER代码', '', '顶部banner插入代码，一般是468*60的图片', 1, 2, '', 10900, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_LICENSE_KEY', '网站授权注册码', '', '', 1, 2, '', 11100, '网站基本信息');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_TYPE', '数据库类型', 'mysql', '目前只支持mysql', 1, 7, 'a:1:{s:5:"mysql";s:5:"mysql";}', 20100, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_CHARSET', '数据库连接编码', 'gbk', '', 1, 7, 'a:6:{s:3:"gbk";s:3:"gbk";s:6:"gb2312";s:6:"gb2312";s:4:"utf8";s:4:"utf8";s:4:"big5";s:4:"big5";s:6:"latin1";s:6:"latin1";s:7:"default";s:7:"default";}', 20120, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_PREFIX', '数据表前缀', 'jieqi', '', 1, 1, '', 20200, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_HOST', '数据库服务器', 'localhost:3307', '', 1, 1, '', 20300, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_USER', '数据库用户名', 'root', '', 1, 1, '', 20400, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_PASS', '数据库密码', 'root', '留空表示不修改密码', 1, 5, '', 20500, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_NAME', '数据库名', 'jieqicms160', '', 1, 1, '', 20600, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DB_PCONNECT', '是否使用持久连接', '0', '', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20700, '数据库设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_IS_OPEN', '网站是否开放', '1', '', 1, 7, 'a:3:{i:1;s:8:"网站开放";i:0;s:8:"网站关闭";i:2;s:18:"开放但禁止登录发表";}', 30100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_CLOSE_INFO', '网站关闭时提示', '网站维护中，请稍后访问......', '', 1, 2, '', 30200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_PROXY_DENIED', '网站是否允许代理访问', '1', '', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 30230, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_THEME_SET', '网站风格设置', 'jieqi160', '', 1, 1, '', 30400, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_TOP_BAR', '顶部通栏代码', '', '', 1, 2, '', 30800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_BOTTOM_BAR', '底部通栏代码', '', '', 1, 2, '', 30900, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_ERROR_MODE', '错误显示模式', '1', '', 1, 7, 'a:3:{i:0;s:10:"不显示错误";i:1;s:8:"显示错误";i:2;s:14:"显示错误和提示";}', 31200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_ALLOW_REGISTER', '是否允许注册', '1', '', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 31300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DENY_RELOGIN', '禁止同一帐号多人登陆', '0', '', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 31320, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_DATE_FORMAT', '日期格式', 'Y-m-d', '', 1, 1, '', 31400, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_TIME_FORMAT', '时间格式', 'H:i:s', '', 1, 1, '', 31500, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_SESSION_EXPRIE', 'session保持时间', '0', '单位为“秒”,设成“0”表示用系统默认参数', 1, 3, '', 31600, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_SESSION_STORAGE', 'session保存方式', 'file', '', 1, 7, 'a:2:{s:2:"db";s:6:"数据库";s:4:"file";s:4:"文件";}', 31700, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_SESSION_SAVEPATH', 'session保存路径', '', '只有在session文件方式保存时有效', 1, 1, '', 31800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_COOKIE_DOMAIN', 'cookie的有效域名', '', '当适用多个子域名时候为了cookie同步，建议这里设置成主域名，如abc.com。留空则使用系统默认值', 1, 1, '', 31820, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_CUSTOM_INCLUDE', '附加载入用户自定义程序', '0', '如果开启本功能，用户可以为每个页面设置一段附加的PHP程序。这种做法容易和系统程序冲突，请斟酌使用！', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 31850, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_ENABLE_CACHE', '是否启用缓存', '0', '', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 32200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_CACHE_LIFETIME', '默认缓存时间', '3600', '单位为“秒”', 1, 3, '', 32300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_CACHE_DIR', '网页缓存路径', 'cache', '支持三种写法：1、只填目录名（指网站跟目录下的子目录名），如： cahce ；2、使用完整路径，如： D:/web/cache ；3、使用Memcached，格式为 memcached://服务地址:端口号，如：memcached://127.0.0.1:11211', 1, 1, '', 32320, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_COMPILED_DIR', '编译文件保存路径', 'compiled', '可使用 dirname 这样的相对路径，或者 /path/dirname 这样的绝对路径', 1, 1, '', 32360, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_USE_GZIP', 'GZIP压缩', '0', '压缩输出有利于提高浏览速度', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 32400, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_SILVER_USAGE', '是否系统银币功能', '0', '冲值时候可选充成金币或银币，后台结算可分开，但对用户是统一使用的', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 32440, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_CHARSET_CONVERT', '是否允许繁简转化', '1', '', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 32450, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_AJAX_PAGE', '是否使用AJAX翻页', '0', '', 1, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 32460, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_EGOLD_NAME', '虚拟货币名称', '虚拟货币', '', 1, 1, '', 32500, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_FORM_MAX', '最大表单宽度', '100%', '一般同整站宽度，可用百分比或数字', 1, 1, '', 32600, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_FORM_MIDDLE', '中等表单宽度', '580', '一般指网站一边有栏目时，另一边允许的宽度，可用百分比或数字', 1, 1, '', 32700, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_FORM_MIN', '最小表单宽度', '400', '一般指网站两边都有栏目时，中间允许的宽度，可用百分比或数字', 1, 1, '', 32767, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_MAX_PAGES', '列表最大页数', '0', '0表示不限制页数', 1, 3, '', 32800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_PROMOTION_VISIT', '访问推广增加贡献值', '0', '访问者通过用户提供的推广链接(如 index.php?fromuid=1)访问网站，推广人所得的贡献值。设置为 0 表示不启用本功能。', 1, 3, '', 33100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'JIEQI_PROMOTION_REGISTER', '注册推广增加贡献值', '0', '访问者通过用户提供的推广链接(如 index.php?fromuid=1)访问网站并注册为会员，推广人所得的贡献值。设置为 0 表示不启用本功能。', 1, 3, '', 33200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'system', 'postdenytimes', '禁止发帖的时间段', '', '请使用 24 小时时段格式，每个时间段一行，留空为不限制。如：每日晚 11:25 到次日早 5:05 可设置为: 23:25-5:05 ；每日早 9:00 到当日下午 2:30 可设置为: 9:00-14:30', 0, 2, '', 40260, '内容检查设置');
-- 
-- 导出表中的数据 `jieqi_system_groups`
-- 

INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (1, '游客', '未注册或者未登陆的访客', 1);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (2, '系统管理员', '最高权限拥有者', 1);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (3, '普通会员', '注册并且已经登陆的会员', 1);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (4, '高级会员', '资深的会员', 0);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (5, 'VIP会员', '收费的会员', 0);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (6, '专栏作家', '普通作家', 0);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (7, '驻站作家', '本站专职作家', 0);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (8, '初级版主', '处理普通事务', 0);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (9, '中级版主', '处理中级事务', 0);
INSERT INTO `jieqi_system_groups` (`groupid`, `name`, `description`, `grouptype`) VALUES (10, '高级版主', '除了系统管理员最高权限', 0);


-- 
-- 导出表中的数据 `jieqi_system_power`
-- 

INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminpanel', '进入管理面板', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminconfig', '管理参数设置', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminpower', '管理权限设置', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'admingroup', '管理用户组', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminuser', '管理用户', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'deluser', '删除用户', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminblock', '管理区块', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminpaylog', '管理在线支付', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminmessage', '管理短消息', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminuserlog', '管理用户日志', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'viewuser', '查看用户列表', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'viewonline', '查看在线用户', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'changegroup', '管理用户等级', '指修改用户组权限（注意：只有系统管理员才能设置系统管理员）', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminvip', '管理用户VIP信息', '修改VIP状态，虚拟货币等', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'sendmessage', '向其他会员发送短信', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'haveparlor', '拥有个人会客室', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'parlorpost', '允许在会客室发帖', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'manageallparlor', '管理所有会客室', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'system', 'adminreport', '管理用户报告', '', '');


-- 
-- 导出表中的数据 `jieqi_system_honors`
-- 

INSERT INTO `jieqi_system_honors` (`honorid`, `caption`, `minscore`, `maxscore`, `setting`, `honortype`) VALUES (1, '新手上路', -9999999, 50, '', 0);
INSERT INTO `jieqi_system_honors` (`honorid`, `caption`, `minscore`, `maxscore`, `setting`, `honortype`) VALUES (2, '普通会员', 50, 200, '', 0);
INSERT INTO `jieqi_system_honors` (`honorid`, `caption`, `minscore`, `maxscore`, `setting`, `honortype`) VALUES (3, '中级会员', 200, 500, '', 0);
INSERT INTO `jieqi_system_honors` (`honorid`, `caption`, `minscore`, `maxscore`, `setting`, `honortype`) VALUES (4, '高级会员', 500, 1000, '', 0);
INSERT INTO `jieqi_system_honors` (`honorid`, `caption`, `minscore`, `maxscore`, `setting`, `honortype`) VALUES (5, '金牌会员', 1000, 3000, '', 0);
INSERT INTO `jieqi_system_honors` (`honorid`, `caption`, `minscore`, `maxscore`, `setting`, `honortype`) VALUES (6, '本站元老', 3000, 9999999, '', 0);

-- 
-- 导出表中的数据 `jieqi_system_right`
-- 

INSERT INTO `jieqi_system_right` (`rid`, `modname`, `rname`, `rtitle`, `rdescription`, `rhonors`) VALUES (0, 'system', 'maxfriends', '最大好友数', '', '');
INSERT INTO `jieqi_system_right` (`rid`, `modname`, `rname`, `rtitle`, `rdescription`, `rhonors`) VALUES (0, 'system', 'maxmessages', '信箱最多消息数', '', '');
INSERT INTO `jieqi_system_right` (`rid`, `modname`, `rname`, `rtitle`, `rdescription`, `rhonors`) VALUES (0, 'system', 'maxdaymsg', '每天允许发消息数', '', '');

-- 
-- 导出表中的数据 `jieqi_system_users`
-- 

INSERT INTO `jieqi_system_users` (`uid`, `siteid`, `uname`, `name`, `pass`, `groupid`, `regdate`, `initial`, `sex`, `email`, `url`, `avatar`, `workid`, `qq`, `icq`, `msn`, `mobile`, `sign`, `intro`, `setting`, `badges`, `lastlogin`, `showsign`, `viewemail`, `notifymode`, `adminemail`, `monthscore`, `weekscore`, `dayscore`, `lastscore`, `experience`, `score`, `egold`, `esilver`, `credit`, `goodnum`, `badnum`, `isvip`, `overtime`, `state`) VALUES(1, 0, 'admin', 'admin', '21232f297a57a5a743894a0e4a801fc3', 2, 1235979949, 'A', 0, 'admin@jieqi.com', '', 2, 0, '', '', '', '', '', '', '', '', 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
