-- 
-- 导出表中的数据 `jieqi_system_blocks`
-- 

INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '分类阅读', 'article', 'block_sort', 'BlockArticleSort', 0, '分类阅读', '', '', '', '', 0, 0, 20100, 0, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '文章搜索', 'article', 'block_search', 'BlockArticleSearch', 1, '文章搜索', '', '', '', '', 0, 0, 20200, 0, 0, 0, 3, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '排 行 榜', 'article', 'block_toplist', 'BlockArticleToplist', 0, '排 行 榜', '', '', '', '', 0, 0, 20300, 0, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '文章总排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '文章总排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'allvisit,15,0,0,0,0', 'block_allvisit.html', 0, 4, 20400, 0, 0, 0, 3, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '文章月排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '文章月排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'monthvisit,15,0,0,0,0', 'block_monthvisit.html', 0, 4, 20500, 0, 0, 0, 3, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '文章周排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '文章周排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'weekvisit,15,0,0,0,0', 'block_weekvisit.html', 0, 4, 20600, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '文章日排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 1, '文章日排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'dayvisit,15,0,0,0,0', 'block_dayvisit.html', 0, 4, 20700, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '原创总排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '原创总排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'allvisit,15,0,1,0,0', 'block_allauthorvisit.html', 0, 4, 20800, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '原创月排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '原创月排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'monthvisit,15,0,1,0,0', 'block_monthauthorvisit.html', 0, 4, 20900, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '原创周排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '原创周排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'weekvisit,15,0,1,0,0', 'block_weekauthorvisit.html', 0, 4, 21000, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '原创日排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '原创日排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'dayvisit,15,0,1,0,0', 'block_dayauthorvisit.html', 0, 4, 21100, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '本站推荐', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '本站推荐', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'toptime,15,0,0,0,0', 'block_toptime.html', 0, 4, 21200, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '总推荐榜', 'article', 'block_articlelist', 'BlockArticleArticlelist', 1, '总推荐榜', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'allvote,15,0,0,0,0', 'block_allvote.html', 0, 4, 21300, 0, 0, 0, 3, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '本月推荐', 'article', 'block_articlelist', 'BlockArticleArticlelist', 1, '本月推荐', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'monthvote,15,0,0,0,0', 'block_monthvote.html', 0, 4, 21400, 0, 0, 0, 3, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '本周推荐', 'article', 'block_articlelist', 'BlockArticleArticlelist', 1, '本周推荐', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'weekvote,15,0,0,0,0', 'block_weekvote.html', 0, 4, 21500, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '本日推荐', 'article', 'block_articlelist', 'BlockArticleArticlelist', 1, '本日推荐', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'dayvote,15,0,0,0,0', 'block_dayvote.html', 0, 4, 21600, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '最近更新', 'article', 'block_articlelist', 'BlockArticleArticlelist', 5, '最近更新', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'lastupdate,15,0,0,0,0', 'block_lastupdate.html', 0, 4, 21700, 0, 0, 0, 3, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '原创更新', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '原创更新', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'lastupdate,15,0,1,0,0', 'block_authorupdate.html', 0, 4, 21800, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '转载更新', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '转载更新', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'lastupdate,15,0,2,0,0', 'block_masterupdate.html', 0, 4, 21900, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '最新入库', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '最新入库', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'postdate,15,0,0,0,0', 'block_postdate.html', 0, 4, 22000, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '最新书评', 'article', 'block_reviewslist', 'BlockArticleReviewslist', 0, '最新书评', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_reviewslist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置四个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是显示行数，使用整数（默认 10）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是指是否置顶书评（默认 0 表示不判断），1 表示只显示置顶书评，2 表示非置顶书评<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是指是否精华书评（默认 0 表示不判断），1 表示只显示精华书评，2 表示非精华书评<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指每条书评最大显示长度，必须是整数（默认 64 ，单位是字节，相当于 32 个汉字）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “15,0,1,64” 表示显示15条最新精华书评。', '', '10,0,0,64', 'block_reviewslist.html', 0, 1, 22100, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '收藏排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 5, '收藏排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'goodnum,15,0,0,0,0', 'block_goodnum.html', 0, 4, 22200, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '字数排行', 'article', 'block_articlelist', 'BlockArticleArticlelist', 5, '字数排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'size,15,0,0,0,0', 'block_size.html', 0, 4, 22300, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '我的原创文章', 'article', 'block_myarticles', 'BlockArticleMyarticles', 0, '我的原创文章', '', '', '', '', 0, 4, 22400, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '我的转载文章', 'article', 'block_transarticles', 'BlockArticleTransarticles', 0, '我的转载文章', '', '', '', '', 0, 4, 22500, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '作家工具箱', 'article', 'block_writerbox', 'BlockArticleWriterbox', 0, '作家工具箱', '', '', '', '', 0, 0, 22600, 1, 0, 0, 0, 0);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '文章列表区块', 'article', 'block_articlelist', 'BlockArticleArticlelist', 0, '文章总排行', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_articlelist.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置六个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排行方式（默认按总访问量），允许以下几种设置：1、“allvisit” - 按总访问量；2、“monthvisit” - 按月访问量；3、“weekvisit” - 按周访问量；4、“dayvisit” - 按日访问量；5、“allvote” - 按总推荐次数；6、“monthvote” - 按月推荐次数；7、“weekvote” - 按周推荐次数；8、“dayvote” - 按日推荐次数；9、“postdate” - 按最新入库；10、“toptime” - 按本站推荐；11、“goodnum” - 按收藏数量；12、“size” - 按文章字数；13、“lastupdate” - 按最近更新；<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示行数，使用整数（默认 15）<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是文章类别（默认 0 表示所有类别），此处使用得是类别序号而不是名称，比如“玄幻小说”类别序号是 3 ，这里就设置成 3，如果要同时选择多个类别，可以用“|”分隔，比如 3|4|7<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是指是否原创（默认 0 表示不判断），1 表示只显示原创作品，2 表示转载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五是指是否全本（默认 0 表示不判断），1 表示只显示全本作品，2 表示连载作品<br>&nbsp;&nbsp;&nbsp;&nbsp;参数六是指显示顺序（默认 0 表示按从大到小排序），1 表示从小到大排序。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数设置中一项或者多项留空均表示使用默认值。例子： “lastupdate,,0,1,0,0” 表示显示15条最近更新的原创作品，其中第二个参数留空，所以使用默认的15条。', '', 'allvisit,15,0,0,0,0', 'block_articlelist.html', 0, 4, 23000, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '文章封面推荐', 'article', 'block_commend', 'BlockArticleCommend', 0, '封面推荐', '&nbsp;&nbsp;&nbsp;&nbsp;本区块允许用户自定义模板和参数，并且不同的设置可以保存成不同的区块。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块默认模板文件为“block_commend.html”，在/modules/article/templates/blocks目录下，如果您定义了另外模板文件，也必须在此目录。模板文件设置留空表示使用默认模板。<br>&nbsp;&nbsp;&nbsp;&nbsp;区块允许设置推荐的文章序号作为参数，不同参数之间用英文“|”分隔。比如： “123|234|456|678” 表示本区块调用这四个序号文章信息显示', '', '', 'block_commend.html', 0, 1, 23100, 0, 0, 0, 0, 2);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户文章', 'article', 'block_uarticles', 'BlockArticleUarticles', 6, '我的文章', '&nbsp;&nbsp;&nbsp;&nbsp;本区块显示某一用户的原创文章<br>&nbsp;&nbsp;&nbsp;&nbsp;允许设置五个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排序字段，允许设置成“lastupdate”-更新时间，“postdate”-发表时间，“articleid”-文章ID，“allvisit”-总点击，“monthvisit”-月点击，“weekvisit”-周点击，“allvote”-总推荐，“monthvote”-月推荐，“weekvote”-周推荐，“size”-字数，“goodnum”-收藏数<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示几条记录，默认10<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是排序方式：0-从大到小，1-从小到大<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是显示哪个用户的友情链接，允许设置成“self”-当前用户，“uid”-url参数里面uid值对应的用户，“0”-所有用户，设置成大于0的一个整数，表示指定这个uid的用户<br>&nbsp;&nbsp;&nbsp;&nbsp;参数五全本标志，0-都显示，1-显示全本，2-显示非全本', '', 'lastupdate,10,0,uid,0', 'block_uarticles.html', 0, 4, 25100, 0, 0, 0, 0, 1);
INSERT INTO `jieqi_system_blocks` (`bid`, `blockname`, `modname`, `filename`, `classname`, `side`, `title`, `description`, `content`, `vars`, `template`, `cachetime`, `contenttype`, `weight`, `showstatus`, `custom`, `canedit`, `publish`, `hasvars`) VALUES(0, '用户书架', 'article', 'block_ubookcase', 'BlockArticleUbookcase', 6, '我的书架', '&nbsp;&nbsp;&nbsp;&nbsp;本区块显示某一用户的书架文章<br>&nbsp;&nbsp;&nbsp;&nbsp;允许设置四个参数，不同参数之间用英文逗号分隔“,”。<br>&nbsp;&nbsp;&nbsp;&nbsp;参数一是排序字段，允许设置成“lastupdate”-更新时间，“joindate”-加入时间，“articleid”-文章ID，“caseid”-书架ID，“lastvisit”-最后访问时间<br>&nbsp;&nbsp;&nbsp;&nbsp;参数二是显示几条记录，默认10<br>&nbsp;&nbsp;&nbsp;&nbsp;参数三是排序方式：0-从大到小，1-从小到大<br>&nbsp;&nbsp;&nbsp;&nbsp;参数四是显示哪个用户的友情链接，允许设置成“self”-当前用户，“uid”-url参数里面uid值对应的用户，“0”-所有用户，设置成大于0的一个整数，表示指定这个uid的用户', '', 'lastupdate,10,0,uid', 'block_ubookcase.html', 0, 4, 25200, 0, 0, 0, 0, 1);

-- 
-- 导出表中的数据 `jieqi_system_configs`
-- 

INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'newreviewnum', '显示几条最新书评', '10', '', 0, 3, '', 11800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'indexcols', '目录页面一行显示几个章节', '4', '', 0, 3, '', 12100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'pagenum', '文章列表一页显示几行', '30', '', 0, 3, '', 12200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'cachenum', '文章列表缓存几个页面', '10', '', 0, 3, '', 12300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'toppagenum', '排行榜一页显示几行', '30', '', 0, 3, '', 12320, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'topcachenum', '排行榜缓存几个页面', '10', '', 0, 3, '', 12350, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'reviewnew', '文章页面显示多少书评', '10', '', 0, 3, '', 12400, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'reviewnum', '书评页面显示多少书评', '50', '', 0, 3, '', 12500, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'notenew', '作家专栏页面显示多少留言', '10', '', 0, 3, '', 12600, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'notenum', '作家会客室显示多少留言', '50', '', 0, 3, '', 12700, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'draftnum', '草稿箱显示几行', '30', '', 0, 3, '', 12800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'reviewneedscore', '发表书评需要积分', '0', '低于此积分的禁止发表书评', 0, 3, '', 12850, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'reviewwidth', '评论显示宽度', '90', '单位是“字节”，1个汉字等于2个字节', 0, 3, '', 12900, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maxreviewsize', '最大评论长度', '0', '单位是“字节”，设为0表示无限制', 0, 3, '', 13000, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'minreviewsize', '最小评论长度', '0', '单位是“字节”，设为0表示无限制', 0, 3, '', 13100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'goodreviewpercent', '精华书评百分比', '10', '百分之', 0, 3, '', 13150, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'reviewenter', '书评允许显示换行', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 13600, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maxbookmarks', '默认书架藏书量', '20', '', 0, 3, '', 13650, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maxmarkclass', '书架最多类别数', '5', '用户书架最多允许分几个类别，设置成0表示不允许分类。', 0, 3, '', 13660, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'hidearticlewords', '文章隐藏单词', '', '多个单词用空格分开', 0, 2, '', 13800, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'textwatermark', '文字水印', '', '指的是隐藏在阅读页面的一些文字，其中<{$randtext}>将被替换成一组随机字符。例如：“<span style="display:none">版权所有：<{$randtext}>杰奇网络</span>”（style="display:none" 是指默认不可见，但是页面上全选复制时候会包含本部分内容）', 0, 2, '', 13850, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'pageimagecode', '阅读页面图片显示代码', '<div class="divimage"><img src="<{$imageurl}>" border="0" class="imagecontent"></div>', '文章生成阅读页面时候，显示图片附件的html代码。其中<{$imageurl}>将被替换成实际图片地址', 0, 2, '', 13860, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'txtarticlehead', 'TXT全文头部附加内容', '', '生成TXT全文下载，内容头部和尾部可以附加一些预想设置的内容，比如本站名字地址。', 0, 2, '', 13870, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'txtarticlefoot', 'TXT全文尾部附加内容', '', '生成TXT全文下载，内容头部和尾部可以附加一些预想设置的内容，比如本站名字地址。', 0, 2, '', 13880, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'authtypeset', '是否允许自动排版', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 14000, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'autotypeset', '默认自动排版', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 14100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'searchtype', '搜索匹配方式', '0', '', 0, 7, 'a:3:{i:0;s:8:"模糊匹配";i:1;s:10:"半模糊匹配";i:2;s:8:"完整匹配";}', 14150, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'minsearchlen', '搜索关键字最少长度', '4', '', 0, 3, '', 14200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maxsearchres', '最大搜索结果数', '300', '', 0, 3, '', 14300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'minsearchtime', '两次搜索间隔时间', '30', '', 0, 3, '', 14400, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'checkappwriter', '申请作者是否需要审核', '1', '需要审核时会员提交申请，管理员审核。不需要审核则用户点申请，直接成为作者', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 14900, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'articlevote', '文章是否允许发起投票', '0', '本项设置是否允许投票和最大允许一个投票选项', 0, 7, 'a:10:{i:0;s:10:"不允许投票";i:2;s:11:"最大2个选项";i:3;s:11:"最大3个选项";i:4;s:11:"最大4个选项";i:5;s:11:"最大5个选项";i:6;s:11:"最大6个选项";i:7;s:11:"最大7个选项";i:8;s:11:"最大8个选项";i:9;s:11:"最大9个选项";i:10;s:12:"最大10个选项";}', 14950, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'writergroup', '默认作者类型', '临时作者', '用户申请作者后默认的类型（如：临时作者）', 0, 1, '', 15000, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'samearticlename', '文章标题是否允许重复', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 15100, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'visitstatnum', '文章点击统计基数', '1', '即用户访问一篇文章算几个点击，设置成 0 的话不进行点击统计', 0, 3, '', 15200, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'eachlinknum', '每篇文章允许互换链接数', '0', '即一篇文章可以在信息页面设置几本站内的书作为推荐，设为0表示开启本功能', 0, 3, '', 15300, '显示控制');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maketxt', '是否生成文本文件', '1', '目前必须生成', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20080, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'txtdir', '文本保存目录', 'txt', '', 0, 1, '', 20100, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'txturl', '访问文本的URL', '', '文本用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 20120, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'makeopf', '是否生成opf文件', '1', '目前自动生成', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20280, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'opfdir', 'OPF文件目录', 'txt', '一般和文本放在同一目录', 0, 1, '', 20300, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'opfurl', '访问OPF的URL', '', 'OPF文件用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 20320, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'makehtml', '是否生成html', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20680, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'htmldir', 'HTML目录', 'html', '', 0, 1, '', 20700, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'htmlurl', '访问HTML的URL', '', 'HTML文件用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 20720, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'htmlfile', 'HTML文件后缀', '.html', '', 0, 7, 'a:2:{s:5:".html";s:5:".html";s:6:".shtml";s:6:".shtml";}', 20800, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'makefull', '是否生成全文阅读', '0', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20820, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'fulldir', '全文阅读目录', 'fulltext', '', 0, 1, '', 20840, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'fullurl', '访问全文阅读的URL', '', '全文阅读用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 20860, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'makezip', '是否生成zip', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 20880, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'zipdir', 'ZIP目录', 'zip', '', 0, 1, '', 20900, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'zipurl', '访问ZIP文件的URL', '', 'ZIP文件用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 20920, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maketxtfull', '是否生成TXT全文', '1', '', 0, 9, 'a:2:{i:1;s:2:"是";i:0;s:2:"否";}', 21100, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'txtfulldir', 'TXT全文目录', 'txtfull', '', 0, 1, '', 21120, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'txtfullurl', '访问TXT全文的URL', '', '用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 21140, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'makeumd', '是否生成UMD电子书', '0', '全部不选表示不生成umd', 0, 10, 'a:4:{i:1;s:7:"全本umd";i:2;s:7:"64K分卷";i:4;s:8:"128K分卷";i:16;s:8:"512K分卷";}', 21200, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'umddir', 'UMD文件目录', 'umd', '', 0, 1, '', 21220, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'umdurl', '访问UMD文件的URL', '', '用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 21240, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'makejar', '是否生成JAR电子书', '0', '全部不选表示不生成jar', 0, 10, 'a:4:{i:1;s:7:"全本jar";i:2;s:7:"64K分卷";i:4;s:8:"128K分卷";i:16;s:8:"512K分卷";}', 21300, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'jardir', 'JAR文件目录', 'jar', '', 0, 1, '', 21320, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'jarurl', '访问JAR文件的URL', '', '用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 21340, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'imagedir', '封面图片保存目录', 'image', '', 0, 1, '', 21780, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'imagetype', '封面图片文件后缀', '.jpg', '', 0, 7, 'a:4:{s:4:".jpg";s:4:".jpg";s:5:".jpeg";s:5:".jpeg";s:4:".gif";s:4:".gif";s:4:".png";s:4:".png";}', 21800, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'imageurl', '访问封面图片的URL', '', '图片用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 21820, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'fakeinfo', '文章信息页面伪静态规则', '', '\r\n伪静态规则是带有替换标记的路径，留空表示不使用伪静态。\r\n允许使用的替换标记有 <{$id}> 文章ID ,<{$id|subdirectory}> 根据文章ID生成的子目录。\r\n如：/files/article/info<{$id|subdirectory}>/<{$id}>.htm', 0, 1, '', 21910, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'fakesort', '文章分类页面伪静态规则', '', '\r\n伪静态规则是带有替换标记的路径，留空表示不使用伪静态。\r\n允许使用的替换标记有 <{$class}> 分类ID ,<{$page}> 页码，<{$page|subdirectory}> 根据页码生成的子目录。\r\n如：/files/article/sort<{$class}><{$page|subdirectory}>/<{$page}>.htm', 0, 1, '', 21920, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'fakeinitial', '首字母分类页面伪静态规则', '', '\r\n伪静态规则是带有替换标记的路径，留空表示不使用伪静态。\r\n允许使用的替换标记有 <{$initial}> 首字母 ,<{$page}> 页码，<{$page|subdirectory}> 根据页码生成的子目录。\r\n如：/files/article/initial<{$initial}><{$page|subdirectory}>/<{$page}>.htm', 0, 1, '', 21930, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'faketoplist', '排行榜页面伪静态规则', '', '\r\n伪静态规则是带有替换标记的路径，留空表示不使用伪静态。\r\n允许使用的替换标记有 <{$sort}> 排行列表 ,<{$page}> 页码，<{$page|subdirectory}> 根据页码生成的子目录。\r\n如：/files/article/top<{$sort}><{$page|subdirectory}>/<{$page}>.htm', 0, 1, '', 21940, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'staticurl', '文章内静态链接根地址', '', '用于文章和程序保存在不同服务器场合，留空表示用系统默认路径', 0, 1, '', 22000, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'dynamicurl', '文章内动态链接根地址', '', '用于文章和程序保存在不同服务器场合，留空表示用系统默认路径', 0, 1, '', 22100, '文件参数');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scorearticle', '发表文章积分', '10', '', 0, 3, '', 30100, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scorechapter', '增加章节积分', '5', '', 0, 3, '', 30200, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scorereview', '发表书评积分', '1', '', 0, 3, '', 30300, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scoregoodreview', '书评精华积分', '1', '', 0, 3, '', 30400, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'dayvotes', '每天允许推荐次数', '1', '', 0, 3, '', 30600, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scoreuservote', '每次推荐增加积分', '0', '', 0, 3, '', 30610, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'uservotescore', '超过推荐次数后继续推荐每次减少积分', '0', '如果设置成 0 则不允许超过次数后继续推荐', 0, 3, '', 30620, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'voteminsize', '多少字数以上的文章才允许推荐', '0', '如果设置成 0 则表示不限制字数', 0, 3, '', 30630, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'addcasescore', '超过书架收藏量后继续收藏每本减少积分', '0', '如果设置成 0 则不允许超过收藏量限制', 0, 3, '', 30640, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scorezipdown', '下载ZIP文件扣积分', '0', '', 0, 3, '', 30650, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scoretxtfulldown', '下载TXT全文扣积分', '0', '', 0, 3, '', 30660, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scoreumddown', '下载UMD文件扣积分', '0', '', 0, 3, '', 30670, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scorejardown', '下载JAR文件扣积分', '0', '', 0, 3, '', 30680, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'vipvotes', 'vip用户默认月票数', '1', '', 0, 3, '', 31100, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'vipvegold', '当月虚拟币消费超过多少增加一个月票', '1000', '', 0, 3, '', 31200, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'scorevipvote', '用户投月票增加积分', '5', '', 0, 3, '', 31300, '积分设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'attachdir', '附件保存目录', 'attachment', '', 0, 1, '', 32767, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'attachtype', '允许上传的附件类型', 'gif jpg jpeg png bmp', '多个附件用空格格开', 0, 1, '', 32767, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maxattachnum', '一次发文最多附件数', '5', '设成 0 就表示禁止附件上传', 0, 3, '', 32767, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maximagesize', '图片附件最大允许几K', '1000', '', 0, 3, '', 32767, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'maxfilesize', '文件附件最大允许几K', '1000', '', 0, 3, '', 32767, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'attachurl', '访问附件的URL', '', '附件用相对路径的话此处留空，否则用完整url，最后不带斜杠', 0, 1, '', 32767, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'attachwater', '图片附件添加水印及位置', '0', '本功能需要 GD 库支持才能使用，对 JPG/PNG/GIF 格式的上传图片有效', 0, 7, 'a:11:{i:0;s:8:"不加水印";i:1;s:8:"顶部居左";i:2;s:8:"顶部居中";i:3;s:8:"顶部居右";i:4;s:8:"中部居左";i:5;s:8:"中部居中";i:6;s:8:"中部居右";i:7;s:8:"底部居左";i:8;s:8:"底部居中";i:9;s:8:"底部居右";i:10;s:8:"随机位置";}', 32810, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'attachwimage', '附件水印图片文件', 'watermark.gif', '允许 JPG/PNG/GIF 格式，默认只需填文件名，放在 modules/article/images 目录下', 0, 1, '', 32820, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'attachwtrans', '水印图片与原图片的融合度', '30', '范围为 1～100 的整数，数值越大水印图片透明度越低。', 0, 3, '', 32830, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'attachwquality', 'jpeg图片质量', '90', '范围为 0～100 的整数，数值越大结果图片效果越好，但尺寸也越大。', 0, 3, '', 32840, '附件设置');
INSERT INTO `jieqi_system_configs` (`cid`, `modname`, `cname`, `ctitle`, `cvalue`, `cdescription`, `cdefine`, `ctype`, `options`, `catorder`, `catname`) VALUES(0, 'article', 'fakestatic', '文章信息和列表页自动生成静态', '0', '本功能用于把文章信息、分类和排行榜生成静态页，而不是伪静态，生成静态页面的路径和上面设置伪静态规则相同', 0, 9, 'a:2:{i:15;s:2:"是";i:0;s:2:"否";}', 21960, '文件参数');
-- 
-- 导出表中的数据 `jieqi_system_modules`
-- 

INSERT INTO `jieqi_system_modules` (`mid`, `name`, `caption`, `description`, `version`, `lastupdate`, `weight`, `publish`, `modtype`) VALUES (0, 'article', '小说连载', '适合于连载的文学系统', 170, 0, 0, 1, 0);

-- 
-- 导出表中的数据 `jieqi_system_power`
-- 

INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'adminconfig', '管理参数设置', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'adminpower', '管理权限设置', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'authorpanel', '进入作家专栏', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'newarticle', '发表文章', '包括发表新文章、并且可以对自己的文章有增加章节、编辑章节和删除章节权限', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'transarticle', '转载文章', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'needcheck', '发表文章不需要审查', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'manageallarticle', '管理他人文章', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'delmyarticle', '删除自己文章', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'delallarticle', '删除他人文章', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'manageallreview', '管理他人书评', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'newdraft', '管理草稿', '创建和管理草稿的权限', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'managesort', '管理分类', '管理文章类别', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'articleupattach', '发文允许上传附件', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'reviewupattach', '书评允许上传附件', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'viewuplog', '查看更新记录', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'newreview', '发表书评', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'articlemodify', '修改文章统计', '', '');
INSERT INTO `jieqi_system_power` (`pid`, `modname`, `pname`, `ptitle`, `pdescription`, `pgroups`) VALUES(0, 'article', 'setwriter', '审核会员申请成为作者', '', '');


-- 
-- 导出表中的数据 `jieqi_system_right`
-- 

INSERT INTO `jieqi_system_right` (`rid`, `modname`, `rname`, `rtitle`, `rdescription`, `rhonors`) VALUES(0, 'article', 'maxbookmarks', '书架最大收藏量', '', '');
INSERT INTO `jieqi_system_right` (`rid`, `modname`, `rname`, `rtitle`, `rdescription`, `rhonors`) VALUES(0, 'article', 'dayvotes', '每天允许推荐次数', '', '');
